name: Tests
on: [pull_request, push]
jobs:
  test_project:
    name: Run All Tests With Pylint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - run: pip install -r requirements.txt
      - run: python manage.py test
      - run: python -m pylint ./api
